backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Directors Cut"
    files:
      - label: "Projects List"
        name: "projects"
        file: "data/projects.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["Film", "Brand", "Motion", "Documentary", "Music Video", "Campaign"]}
              - {label: "Description", name: "desc", widget: "text"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Year", name: "year", widget: "string"}

  - name: "writings"
    label: "Writings"
    folder: "writings/posts"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Poetry", "Prose", "Essay", "Story"]}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}